# Default values for credit-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

tlpims-service:
  replicaCount: 1
  image: frontend:v1.0
  ingress:
    enabled: true
    rules:
    - path: /
      pathRewrite: ""
      name: frontend