# Default values for mongodb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

accessPort: 31017

users:
  - name: admin
    password: admin
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin
      - name: readWriteAnyDatabase
        db: admin