# Default values for credit-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

tlpims-service:
  replicaCount: 1
  image: order-service:v1.0
  environment:
    - name: MessageHandling__HostName
      value: rabbitmq-cluster
    - name: MongoConnection__HostName
      value: mongodb-cluster-0.mongodb-cluster-svc
    - name: MongoConnection__Credentials__Username
      value: admin
    - name: MongoConnection__Credentials__Password
      value: admin
  ingress:
    enabled: true
    rules:
    - path: /order/swagger
      pathRewrite: /swagger
      name: swagger
    - path: /api/order
      name: api