{{- if .Values.ingress.enabled }}
{{- $fullName := include "tlpims-service.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: kubernetes.local
    http:
      paths:
      - path: {{ .Values.ingress.path }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ .Values.containerPort }}
{{- end }}