version: "3.9"
services:
  creditservice:
    build:
      context: .
      dockerfile: ./CreditService/Dockerfile
    environment:
      MessageHandling__HostName: rabbit
      MongoConnection__HostName: mongo
    ports:
      - "8001:80"

  inventoryservice:
    build:
      context: .
      dockerfile: ./InventoryService/Dockerfile
    environment:
      MessageHandling__HostName: rabbit
      MongoConnection__HostName: mongo
    ports:
      - "8002:80"

  orderservice:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
    environment:
      MessageHandling__HostName: rabbit
      MongoConnection__HostName: mongo
    ports:
      - "8003:80"

  shipmentservice:
    build:
      context: .
      dockerfile: ./ShipmentService/Dockerfile
    environment:
      MessageHandling__HostName: rabbit
    ports:
      - "8004:80"

  rabbit:
    image: rabbitmq:management
    expose:
      - "5672"
    ports:
      - "15672:15672"
  mongo:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"