# Default values for credit-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

tlpims-service:
  replicaCount: 1
  image: inventory-service:v1.1
  environment:
    - name: MessageHandling__HostName
      value: cluster-rabbitmq-cluster
    - name: MongoConnection__HostName
      value: mongodb-mongodb-cluster-svc
