{{- if .Values.management.enabled }}
{{- $fullName := include "rabbitmq-cluster.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  ingressClassName: nginx
  rules:
  - host: kubernetes.local
    http:
      paths:
      - path: {{ .Values.management.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: 15672
{{- end }}