
{{- $fullName := include "mongodb-cluster.fullname" . -}}
{{- range $user := .Values.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $user.name }}-password
type: Opaque
stringData:
  password: {{ $user.password }}
{{- end }}